import SwiftUI

struct SessionInsightsCardView: View {
    let session: FocusSession

    private var insights: [SessionInsight] {
        SessionInsightEngine.insights(for: session)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .firstTextBaseline) {
                Text("Session insights")
                    .font(.headline)

                Spacer()

                Text("Local rules")
                    .font(.caption2)
                    .fontWeight(.semibold)
                    .foregroundStyle(.secondary)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 4)
                    .background(
                        Capsule()
                            .fill(Color.secondary.opacity(0.12))
                    )
            }

            VStack(alignment: .leading, spacing: 8) {
                ForEach(insights) { insight in
                    insightRow(insight)
                }
            }

            Text("These insights are generated by deterministic local rules, not by AI.")
                .font(.caption2)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(14)
        .frame(maxWidth: .infinity, alignment: .topLeading)
        .background(
            RoundedRectangle(cornerRadius: 15)
                .fill(Color.secondary.opacity(0.09))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 15)
                .stroke(Color.secondary.opacity(0.14), lineWidth: 1)
        )
    }

    private func insightRow(_ insight: SessionInsight) -> some View {
        HStack(alignment: .top, spacing: 10) {
            Text("•")
                .font(.caption)
                .fontWeight(.bold)
                .foregroundStyle(.secondary)
                .frame(width: 10)

            VStack(alignment: .leading, spacing: 3) {
                HStack(alignment: .firstTextBaseline) {
                    Text(insight.title)
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    Spacer()

                    Text(insight.value)
                        .font(.caption)
                        .fontWeight(.semibold)
                        .lineLimit(1)
                        .minimumScaleFactor(0.8)
                }

                Text(insight.detail)
                    .font(.caption2)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
        .padding(9)
        .background(
            RoundedRectangle(cornerRadius: 11)
                .fill(Color.secondary.opacity(0.075))
        )
    }
}
